In [1]:
import numpy as np


In [2]:
# List of functions explained 
function1 = np.linalg.det
function2 = np.inner
function3 = np.sort
function4 = np.linalg.solve
function5 = np.linalg.inv

In [3]:
# Example 1 - working (change this)
arr1 = [[1, 2], 
        [3, 4.]]
np.linalg.det(arr1)

-2.0000000000000004

In [4]:
# Example 2 - working
a=np.array([[1,1],[1,1]])
np.linalg.det(a)

0.0

In [5]:

# Example 3 - breaking (to illustrate when it breaks)
arr2 = [[1, 2], 
        [3, 4.],
       [1,2]]
np.linalg.det(arr2)


LinAlgError: Last 2 dimensions of the array must be square

## For multidimensional arrays, the last two dimensions must be equal. Hence, we have an error here so we cannot evaluate the determinant here.

## For multidimensional arrays, the last two dimensions must be equal.Here, last two dimensions are unequal. Hence, we have an error here so we cannot evaluate the determinant here.Last 2 dimensions of the array must be square to fix LinAlgError

In [6]:
# Example 1 - working
arr = np.array([[7,1],[5,9],[8,3]])
np.sort(arr)

array([[1, 7],
       [5, 9],
       [3, 8]])

In [7]:
# Example 2 - working
arr = np.array([[7,1],[5,9],[8,3]])
np.sort(arr,axis=0)

array([[5, 1],
       [7, 3],
       [8, 9]])

In [8]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.array([[7,1],[5,9],[8,3]])
np.sort(arr,axis20)

NameError: name 'axis20' is not defined

### In this example we have specified the wrong axis so it breaks It can be fixed by either continuing with default axis or giving the axis as 0 or 1 .

### Sorting helps to putting something in a sequence.

In [11]:
# Example 1 - working
a=np.array([[2,3],[1,2]])
b=np.array([8,5])
np.linalg.solve(a, b.reshape(2,1))

array([[1.],
       [2.]])

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
a=np.array([[1,1],[2,2]])
b=np.array([1,3])

np.linalg.solve(a,b.reshape(2,1))

LinAlgError: Singular matrix

#### Here, matrix 'a' is singular, which means its determinant is zero.So it causes LinAlgError.Here, matrix 'a' is singular, which means its determinant is zero.So it causes LinAlgError.

#### This function is widely used to solve the system of linear equations and has wide spectrum of applicability in various fields of science and mathematics.

In [13]:
# Example 1 - working
a = np.array([[2,6], 
              [-1,4]])
np.linalg.inv(a)

array([[ 0.28571429, -0.42857143],
       [ 0.07142857,  0.14285714]])

In [14]:
# Example 2 - working
a = np.array([[1,2,3],
             [5,4,8],
             [2,-4,1]])
np.linalg.inv(a)

array([[-1.38461538,  0.53846154, -0.15384615],
       [-0.42307692,  0.19230769, -0.26923077],
       [ 1.07692308, -0.30769231,  0.23076923]])

In [15]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array([[1,3], 
              [2,6]])
np.linalg.inv(a)

LinAlgError: Singular matrix

##### Matrix 'a' is a singular matrix.So, inverse does not exist. It causes LinAlgError.

##### This function helps to find inverse of matrices and hence it plays a vital role in maths and science.

In [16]:
jovian.submit(assignment="zero-to-pandas-a2")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "btech15277-18/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/btech15277-18/numpy-array-operations
[jovian] Submitting assignment..
[jovian] Verify your submission at https://jovian.ai/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
